TARGET = pyrcc4
TEMPLATE = app
QT -= gui
QT += xml
CONFIG += warn_on release
CONFIG -= android_install
target.path = /usr/bin
INSTALLS += target
INCLUDEPATH += /home/pi/Github/ProjM124/PyQt-x11-gpl-4.11.4/pyrcc
VPATH = /home/pi/Github/ProjM124/PyQt-x11-gpl-4.11.4/pyrcc
HEADERS = rcc.h
SOURCES = main.cpp rcc.cpp