/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.18.1
 *
 * Copyright (c) 2015 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of PyQt4.
 * 
 * This file may be used under the terms of the GNU General Public License
 * version 3.0 as published by the Free Software Foundation and appearing in
 * the file LICENSE included in the packaging of this file.  Please review the
 * following information to ensure the GNU General Public License version 3.0
 * requirements will be met: http://www.gnu.org/copyleft/gpl.html.
 * 
 * If you do not wish to use this file under the terms of the GPL version 3.0
 * then you may purchase a commercial license.  For more information contact
 * info@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#include "sipAPIQtGui.h"

#line 31 "/home/pi/Github/ProjM124/PyQt-x11-gpl-4.11.4/sip/QtGui/qapplication.sip"
#include <qapplication.h>
#line 29 "/home/pi/Github/ProjM124/PyQt-x11-gpl-4.11.4/QtGui/sipQtGuiXEvent.cpp"



extern "C" {static int convertTo_XEvent(PyObject *, void **, int *, PyObject *);}
static int convertTo_XEvent(PyObject *sipPy,void **sipCppPtrV,int *sipIsErr,PyObject *)
{
    XEvent **sipCppPtr = reinterpret_cast<XEvent **>(sipCppPtrV);

#line 35 "/home/pi/Github/ProjM124/PyQt-x11-gpl-4.11.4/sip/QtGui/qapplication.sip"
    void *addr = sipConvertToVoidPtr(sipPy);

    if (!sipIsErr)
        return !PyErr_Occurred();

    *sipCppPtr = reinterpret_cast<XEvent *>(addr);

    return 0;
#line 47 "/home/pi/Github/ProjM124/PyQt-x11-gpl-4.11.4/QtGui/sipQtGuiXEvent.cpp"
}


extern "C" {static PyObject *convertFrom_XEvent(void *, PyObject *);}
static PyObject *convertFrom_XEvent(void *sipCppV, PyObject *)
{
   XEvent *sipCpp = reinterpret_cast<XEvent *>(sipCppV);

#line 46 "/home/pi/Github/ProjM124/PyQt-x11-gpl-4.11.4/sip/QtGui/qapplication.sip"
    return sipConvertFromVoidPtr(sipCpp);
#line 58 "/home/pi/Github/ProjM124/PyQt-x11-gpl-4.11.4/QtGui/sipQtGuiXEvent.cpp"
}


sipMappedTypeDef sipTypeDef_QtGui_XEvent = {
    {
        -1,
        0,
        0,
        SIP_TYPE_MAPPED,
        sipNameNr_XEvent,
        {0}
    },
    {
        -1,
        {0, 0, 1},
        0, 0,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
    },
    0,
    0,
    0,
    0,
    convertTo_XEvent,
    convertFrom_XEvent
};
